on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/rust-toolchain.toml') }}

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- -D warnings

      - name: Check docs
        uses: actions-rs/cargo@v1
        with:
          command: rustdoc
          args: --lib -- -D warnings --document-private-items

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Setup Miri
        run: cargo miri setup

      # Note this currently takes a long time because I _do_ run the quicktests
      # with Miri. For now, that's desired.
      - name: Run unsafe BST tests with Miri
        run: cargo miri test bangsafe --verbose
